services:
  app:
    build:
      context: .
      args:
        VITE_API_URL_PROD: /api/v1
    image: ship-app:2.2.1
    container_name: ship-quote-app

    ports:
      - "8081:3000"

    environment:
      NODE_ENV: production
      DEFAULT_COUNTRY: ES
      API_URL: 0.0.0.0
      COUNTRIES_API_ENABLED: false
      SHIP_ADMIN_USER: admin@admin.com
      SHIP_ADMIN_PASS: 123456
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/shipQuote-db

    depends_on:
      - mongo
      - loki

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:8
    container_name: ship-mongo

    volumes:
      - mongo_data:/data/db

  # -------------------------
  # LOKI (almacenamiento logs)
  # -------------------------
  loki:
    image: grafana/loki:3.6.6
    container_name: ship-loki

    ports:
      - "3100:3100"

    volumes:
      - ./infra/monitoring/loki/config.yml:/etc/loki/config.yml
      - loki_data:/loki

    command: -config.file=/etc/loki/config.yml

  # -------------------------
  # ALLOY (lector logs docker)
  # -------------------------
  alloy:
    image: grafana/alloy:v1.20.0
    container_name: ship-alloy

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy_data:/var/lib/alloy/data
      - ./infra/monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro

    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

    depends_on:
      - loki

  # -------------------------
  # GRAFANA (visualización)
  # -------------------------
  grafana:
    image: grafana/grafana:13.2.2
    container_name: ship-grafana

    ports:
      - "3001:3000"

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

    depends_on:
      - loki

    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mongo_data:
  loki_data:
  grafana_data:
  alloy_data: