services:
  app:
    build:
      context: .
      args:
        VITE_API_URL: http://localhost:8080/api/v1

    container_name: ship-quote-app

    ports:
      - "8080:3000"

    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/shipQuote-db

    depends_on:
      - mongo

  mongo:
    image: mongo:8

    container_name: ship-quote-mongo

    ports:
      - "27018:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: