{
 "title": "Ship API",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {}
   },
   {
    "name": "status",
    "label": "status",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total de peticiones 5m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time({service=\"ship-quote-api\"}[5m])\n)"
    }
   ]
  },
  {
   "title": "Peticiones por minuto",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  count_over_time({service=\"ship-quote-api\"}[1m])\n)"
    }
   ]
  },
  {
   "title": "Códigos HTTP",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (\n  count_over_time({service=\"ship-quote-api\"}[5m])\n)"
    }
   ]
  },
  {
   "title": "Tiempo avg 10min últimos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  {service=\"ship-quote-api\"}\n  | json\n  | unwrap responseTime\n  [10m]\n)"
    }
   ]
  },
  {
   "title": "Tiempo avg 30min últimos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  {service=\"ship-quote-api\"}\n  | json\n  | unwrap responseTime\n  [30m]\n)"
    }
   ]
  },
  {
   "title": "Warning últimos 10m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {service=\"ship-quote-api\", level=\"warn\"}[10m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{service=\"$service\", status=~\"$status\"}\n| json\n| line_format \"[{{.level}}] {{.method}} {{.status}} {{.service}} {{.path}} ({{.responseTime}}ms) | {{.message}} \""
    }
   ]
  }
 ]
}