name: Build and Deploy shipQuote

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}


      - name: Build image
        run: |
          docker build \
            --build-arg VITE_API_URL_PROD=http://81.46.212.167:8089/api/v1 \
            -t $REGISTRY/$IMAGE_NAME:IMAGE_TAG \
            .

      - name: Push image
        run: |
          docker push \
            $REGISTRY/$IMAGE_NAME:IMAGE_TAG

  
  deploy:
    name: Deploy Docker shipQuote
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      
    steps:

      - name: Copy deployment files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.prod.yml,infra/"
          target: "opt/ship-quote"


      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd opt/ship-quote

            cat > .env << 'EOF'
            ${{ secrets.PRODUCTION_ENV }}
            EOF

            echo "${{ secrets.GHCR_TOKEN }}" | \
              docker login ghcr.io \
              --username "${{ secrets.GHCR_USERNAME }}" \
              --password-stdin

            export IMAGE_TAG=${{ github.sha }}

            docker compose \
              -f docker-compose.prod.yml \
              -p ship-quote-app \
              pull

            docker compose \
              -f docker-compose.prod.yml \
              -p ship-quote-app \
              up -d

            echo "Cleaning unused images..."