export const provincesData = [
    { name: "Álava", adminCode: "VI", postalCode: "01" },
    { name: "Albacete", adminCode: "AB", postalCode: "02" },
    { name: "Alicante", adminCode: "A", postalCode: "03" },
    { name: "Almería", adminCode: "AL", postalCode: "04" },
    { name: "Asturias", adminCode: "O", postalCode: "33" },
    { name: "Ávila", adminCode: "AV", postalCode: "05" },
    { name: "Badajoz", adminCode: "BA", postalCode: "06" },
    { name: "Barcelona", adminCode: "B", postalCode: "08" },
    { name: "Burgos", adminCode: "BU", postalCode: "09" },
    { name: "Cáceres", adminCode: "CC", postalCode: "10" },
    { name: "Cádiz", adminCode: "CA", postalCode: "11" },
    { name: "Cantabria", adminCode: "S", postalCode: "39" },
    { name: "Castellón", adminCode: "CS", postalCode: "12" },
    { name: "Ciudad Real", adminCode: "CR", postalCode: "13" },
    { name: "Córdoba", adminCode: "CO", postalCode: "14" },
    { name: "Cuenca", adminCode: "CU", postalCode: "16" },
    { name: "Gerona", adminCode: "GI", postalCode: "17" },
    { name: "Granada", adminCode: "GR", postalCode: "18" },
    { name: "Guadalajara", adminCode: "GU", postalCode: "19" },
    { name: "Guipúzcoa", adminCode: "SS", postalCode: "20" },
    { name: "Huelva", adminCode: "H", postalCode: "21" },
    { name: "Huesca", adminCode: "HU", postalCode: "22" },
    { name: "Jaén", adminCode: "J", postalCode: "23" },
    { name: "León", adminCode: "LE", postalCode: "24" },
    { name: "Lérida", adminCode: "L", postalCode: "25" },
    { name: "La Rioja", adminCode: "LO", postalCode: "26" },
    { name: "Lugo", adminCode: "LU", postalCode: "27" },
    { name: "Madrid", adminCode: "M", postalCode: "28" },
    { name: "Málaga", adminCode: "MA", postalCode: "29" },
    { name: "Murcia", adminCode: "MU", postalCode: "30" },
    { name: "Navarra", adminCode: "NA", postalCode: "31" },
    { name: "Orense", adminCode: "OR", postalCode: "32" },
    { name: "Palencia", adminCode: "P", postalCode: "34" },
    { name: "Pontevedra", adminCode: "PO", postalCode: "36" },
    { name: "Salamanca", adminCode: "SA", postalCode: "37" },
    { name: "Santa Cruz de Tenerife", adminCode: "TF", postalCode: "38" },
    { name: "Segovia", adminCode: "SG", postalCode: "40" },
    { name: "Sevilla", adminCode: "SE", postalCode: "41" },
    { name: "Soria", adminCode: "SO", postalCode: "42" },
    { name: "Tarragona", adminCode: "T", postalCode: "43" },
    { name: "Teruel", adminCode: "TE", postalCode: "44" },
    { name: "Toledo", adminCode: "TO", postalCode: "45" },
    { name: "Valencia", adminCode: "V", postalCode: "46" },
    { name: "Valladolid", adminCode: "VA", postalCode: "47" },
    { name: "Vizcaya", adminCode: "BI", postalCode: "48" },
    { name: "Zamora", adminCode: "ZA", postalCode: "49" },
    { name: "Zaragoza", adminCode: "Z", postalCode: "50" },
    { name: "Ceuta", adminCode: "CE", postalCode: "51" },
    { name: "Melilla", adminCode: "ML", postalCode: "52" }
];

export const specialIslands = [
    { name: "Gran Canaria", adminCode: "GC-GC", postalCode: "35" },
    { name: "Tenerife", adminCode: "TF-TE", postalCode: "38" },
    { name: "Fuerteventura", adminCode: "GC-FU", postalCode: "35" },
    { name: "Lanzarote", adminCode: "GC-LA", postalCode: "35" },
    { name: "La Palma", adminCode: "TF-LP", postalCode: "38" },
    { name: "La Gomera", adminCode: "TF-LG", postalCode: "38" },
    { name: "El Hierro", adminCode: "TF-EH", postalCode: "38" },
    { name: "Mallorca", adminCode: "IB-ML", postalCode: "07" },
    { name: "Menorca", adminCode: "IB-MN", postalCode: "07" },
    { name: "Ibiza", adminCode: "IB-IB", postalCode: "07" },
    { name: "Formentera", adminCode: "IB-FE", postalCode: "07" }
];