
export const provincesData = [
    { name: "Álava", admin_code: "VI" },
    { name: "Albacete", admin_code: "AB" },
    { name: "Alicante", admin_code: "A" },
    { name: "Almería", admin_code: "AL" },
    { name: "Asturias", admin_code: "O" },
    { name: "Ávila", admin_code: "AV" },
    { name: "Badajoz", admin_code: "BA" },
    { name: "Barcelona", admin_code: "B" },
    { name: "Burgos", admin_code: "BU" },
    { name: "Cáceres", admin_code: "CC" },
    { name: "Cádiz", admin_code: "CA" },
    { name: "Cantabria", admin_code: "S" },
    { name: "Castellón", admin_code: "CS" },
    { name: "Ciudad Real", admin_code: "CR" },
    { name: "Córdoba", admin_code: "CO" },
    { name: "Cuenca", admin_code: "CU" },
    { name: "Gerona", admin_code: "GI" },
    { name: "Granada", admin_code: "GR" },
    { name: "Guadalajara", admin_code: "GU" },
    { name: "Guipúzcoa", admin_code: "SS" },
    { name: "Huelva", admin_code: "H" },
    { name: "Huesca", admin_code: "HU" },
    { name: "Jaén", admin_code: "J" },
    { name: "León", admin_code: "LE" },
    { name: "Lérida", admin_code: "L" },
    { name: "La Rioja", admin_code: "LO" },
    { name: "Lugo", admin_code: "LU" },
    { name: "Madrid", admin_code: "M" },
    { name: "Málaga", admin_code: "MA" },
    { name: "Murcia", admin_code: "MU" },
    { name: "Navarra", admin_code: "NA" },
    { name: "Orense", admin_code: "OR" },
    { name: "Palencia", admin_code: "P" },
    { name: "Pontevedra", admin_code: "PO" },
    { name: "Salamanca", admin_code: "SA" },
    { name: "Santa Cruz de Tenerife", admin_code: "TF" },
    { name: "Segovia", admin_code: "SG" },
    { name: "Sevilla", admin_code: "SE" },
    { name: "Soria", admin_code: "SO" },
    { name: "Tarragona", admin_code: "T" },
    { name: "Teruel", admin_code: "TE" },
    { name: "Toledo", admin_code: "TO" },
    { name: "Valencia", admin_code: "V" },
    { name: "Valladolid", admin_code: "VA" },
    { name: "Vizcaya", admin_code: "BI" },
    { name: "Zamora", admin_code: "ZA" },
    { name: "Zaragoza", admin_code: "Z" },
    { name: "Ceuta", admin_code: "CE" },
    { name: "Melilla", admin_code: "ML" }
];

export const specialIslands = [
    { name: "Gran Canaria", admin_code: "GC-GC" },
    { name: "Tenerife", admin_code: "TF-TE" },
    { name: "Fuerteventura", admin_code: "GC-FU" },
    { name: "Lanzarote", admin_code: "GC-LA" },
    { name: "La Palma", admin_code: "TF-LP" },
    { name: "La Gomera", admin_code: "TF-LG" },
    { name: "El Hierro", admin_code: "TF-EH" },
    { name: "Mallorca", admin_code: "IB-ML" },
    { name: "Menorca", admin_code: "IB-MN" },
    { name: "Ibiza", admin_code: "IB-IB" },
    { name: "Formentera", admin_code: "IB-FE" }
];